### ISSUE TITLE
隙間を埋めよう

### ISSUE THREAD

**Issue by c0b21007** [c0b21059c5/ProjExD#4]
https://github.com/c0b21059c5/ProjExD/blob/59f706f9f9388fbcffcbabe53d0b9a26f0ab712a/Ex02/calc.py#L26
ACの横と0の横に隙間があるので、サイズを変えて埋めてあげると見やすい電卓になると思います。

**Comment by c0b21059c5** [comment]
変更しました。
ありがとうございます。
