### ISSUE TITLE
まとめられるかもしれません。

### ISSUE THREAD

**Issue by c0b210910f** [c0b21059c5/ProjExD#5]
https://github.com/c0b21059c5/ProjExD/blob/a314d111f9500bf711d7ac49b2b946fa6b672666/ex03/maze.py#L24
ここの3行がif文のたびに呼び出されていてもう少しきれいな書き方があるかもしれません

**Comment by c0b21059c5** [comment]
私の技術不足でif文をまとめることが出来ませんでした。
誠に申し訳ございませんでした。
今後はこのようなことがないよう尽力したいと思います
