### ISSUE TITLE
二つ目の爆弾のコードについて

### ISSUE THREAD

**Issue by c0b210910f** [c0b21059c5/ProjExD#7]
https://github.com/c0b21059c5/ProjExD/blob/31a6f9ada0b92fbf856d5b52983d0ea967937231/ex04/dodge_bomb.py#L43
もう少し工夫すればきれいなコードになると思います

**Comment by c0b21059c5** [comment]
私の技術不足でfor文でまとめることが出来ませんでした。
誠に申し訳ございませんでした。
今後はこのようなことがないよう尽力したいと思います
