### ISSUE TITLE
繰り返し

### ISSUE THREAD

**Issue by c0b21007** [c0b21059c5/ProjExD#8]
https://github.com/c0b21059c5/ProjExD/blob/31a6f9ada0b92fbf856d5b52983d0ea967937231/ex04/dodge_bomb.py#L43
同じ爆弾を複数作るなら、for文などを使うことでコンパクトにできると思います

**Comment by c0b21007** [comment]
試したのですが、うまくできませんでした。
次までに勉強しておきます

**Comment by c0b21059c5** [comment]
私の技術不足でfor文でまとめることが出来ませんでした。
誠に申し訳ございませんでした。
今後はこのようなことがないよう尽力したいと思います
